---
#     _____                    _                         _
#    / ____|                  | |                       | |
#   | (___   ___ ___  _ __ ___| |__   ___   __ _ _ __ __| |
#    \___ \ / __/ _ \| '__/ _ \ '_ \ / _ \ / _` | '__/ _` |
#    ____) | (_| (_) | | |  __/ |_) | (_) | (_| | | | (_| |
#   |_____/ \___\___/|_|  \___|_.__/ \___/ \__,_|_|  \__,_|
#
#

# Time between a scoreboard update.
# RECOMMANDED: 2 seconds
update_time: 40 # TICKS 20 = 1 second

options:
  # {faction_name} {faction_rank} {faction_power}
  PiggyFactions: false
  # {faction_name} {faction_power}
  FactionsPro: false
  # {faction_name} {faction_rank} {faction_power} {faction_money}
  SimpleFaction: false
  # {money}
  EconomyAPI: false
  # {rank} {prefix} {suffix}
  PurePerms: false
  # {island_blocks} {island_members} {island_rank} {island_size}
  SkyBlock: false
  # {device}
  SeeDevice: false
  # {bounty}
  Bounty: false
  # {prisons_rank} {prisons_prestige}
  Prisons: false
  # {onlinetime_session} {onlinetime_total}
  OnlineTime: false
  # {combatlogger_time}
  CombatLogger: false
  # {fightlogger_time}
  FightLogger: false
  # {myplot_owner} {myplot_id}
  MyPlot: false
  # {coins}
  CoinsSystem: false
  # {kills} {deaths} {kdr}
  KDR: false
  # {votes} {maxvotes}
  VoteParty: false
  # {balance}
  BankUI: false
  # {island_members} {island_rank} {island_size} {island_value} {island_locked_status}
  RedSkyBlock: false
  # {vanish_fake_count}
  VanishV2: false
  # {balance.currencyName} -> Replace "currencyName" by the currency name
  MultiEconomy: false
  # {rank} {prefix}
  RankSystem: false
  # {MultiServer.online} {MultiServer.Maxonline}
  MultiServerCounter: false
  # {god}
  Godmode: false
  # {faction_name} {faction_rank} {faction_power} {faction_level} {faction_xp} {faction_message} {faction_description} {faction_visibility}
  FactionMaster: false

# BASE VARIABLES : {ping} {tps} {name} {online} {max_online} {level} {x} {y} {z} {ip} {port} {uid} {xuid} {health} {max_health} {food} {max_food} {gamemode} {scale} {date} {xplevel}

per_world: false
title: "§6Scoreboard"
lines:
    - "line1"
    - "line2"

# Edit just if per_world is on true
worlds:
  world:
    title: "§6Scoreboard"
    lines:
      - "line1"
      - "line2"

# true or false if you want the command for disable the scoreboard
command: false
command_description: "Hide or show the scoreboard"
command_success_hide: "§aYou have successfully hidden the scoreboard"
command_success_show: "§aYou have successfully displayed the scoreboard"

# Text for all the plugins using enable/disable functions (GodMode, Fly, and more)
enable: "§aEnable"
disable: "§cDisable"

# Put on true only if you have activated an Economy Support and if you want to convert the money text (Ex: 100000 = 100K 1000000 = 1M 1000000000 = 1B)
# Support : EconomyAPI, MultiEconomy, BankUI, CoinsSystem
convert_money: false

# Here, you can change the date format. All formats are available here https://www.php.net/manual/fr/datetime.format.php
date_format: "m/d/Y"

...
